name: Auto Request Copilot Review

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  request-copilot-review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Request review from Copilot
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: ['copilot']
              });
              console.log('✓ Successfully requested review from @copilot');
            } catch (error) {
              console.log('Note: Could not add @copilot as reviewer:', error.message);
              console.log('This is expected if @copilot is not a collaborator');
            }
